default:
    tags:
      - angular
      - demo
stages:
    - build
build-stage:
    stage: build
    script:
        # - cd dotnet
        - dotnet --version
        - dotnet restore
        - dotnet build
